In [1]:
import numpy as np 
import pandas as pd
import pyfmi 

In [2]:
def cost_of_comfort(ts, csp, hsp, idf_steps_per_hour=6):
    model = pyfmi.load_fmu('model.fmu')
    day = ts // 86400.
    ts = 86400. * day # starting from midnight
    te = ts + 86400.*30 # 30 days

    options = model.simulate_options()
    dt = 3600./idf_steps_per_hour
    ncp = (te - ts)/dt
    options['ncp'] = int(ncp)

    # construct constant inputs
    t = np.linspace(ts, te, int(ncp))
    csp = csp*np.ones_like(t)
    hsp = hsp*np.ones_like(t)
    u_traj = np.vstack((t, csp, hsp)).T
    res = model.simulate(ts, te, input=(['csp', 'hsp'], u_traj), options=options)

    # get energy consumption
    power_in_W = res['hvac_power']
    total_energy = power_in_W.sum() * dt / 3600./1000. # kWh

    # remove from memory
    model.terminate()
    del model
    return total_energy

In [3]:
e1 = cost_of_comfort(0, 22, 19)
e2 = cost_of_comfort(0, 22, 20)
e2 - e1

Reading input and weather file for preprocessor program.
The IDF version of the input file ///tmp/JModelica.org/jm_tmp7cx1wykg//resources//model.idf starts with 22
Successfully finish reading weather file.
This is the Begin Month: 1
Time (0) set is smaller than minimun allowed (1 day). Day will be set to 1.
This is the Day of the Begin Month: 1
This is the End Month: 1
This is the Day of the End Month: 30
This is the New Day of Week: SUNDAY
Running EPMacro...
ExpandObjects Started.
 Begin reading Energy+.idd file.
 Done reading Energy+.idd file.
ExpandObjects Finished. Time:     0.029
EnergyPlus Starting
EnergyPlus, Version 22.2.0-c249759bad, YMD=2023.10.23 21:00
Initializing Response Factors
Calculating CTFs for "EXTERIOR WALL"
Calculating CTFs for "INTERIORFURNISHINGS"
Calculating CTFs for "EXTERIOR FLOOR"
Calculating CTFs for "INTERIOR FLOOR"
Calculating CTFs for "INTERIOR CEILING"
Calculating CTFs for "EXTERIOR ROOF"
Calculating CTFs for "EXTERIOR DOOR"
Calculating CTFs for "GABLE_

EnergyPlus Completed Successfully.


Reading input and weather file for preprocessor program.
The IDF version of the input file ///tmp/JModelica.org/jm_tmpb9gf_zmk//resources//model.idf starts with 22
Successfully finish reading weather file.
This is the Begin Month: 1
Time (0) set is smaller than minimun allowed (1 day). Day will be set to 1.
This is the Day of the Begin Month: 1
This is the End Month: 1
This is the Day of the End Month: 30
This is the New Day of Week: SUNDAY
Running EPMacro...
ExpandObjects Started.
 Begin reading Energy+.idd file.
 Done reading Energy+.idd file.
ExpandObjects Finished. Time:     0.027
EnergyPlus Starting
EnergyPlus, Version 22.2.0-c249759bad, YMD=2023.10.23 21:00
Initializing Response Factors
Calculating CTFs for "EXTERIOR WALL"
Calculating CTFs for "INTERIORFURNISHINGS"
Calculating CTFs for "EXTERIOR FLOOR"
Calculating CTFs for "INTERIOR FLOOR"
Calculating CTFs for "INTERIOR CEILING"
Calculating CTFs for "EXTERIOR ROOF"
Calculating CTFs for "EXTERIOR DOOR"
Calculating CTFs for "GABLE_

EnergyPlus Completed Successfully.


114.03086061005911

In [4]:
import collections 

model = pyfmi.load_fmu('model.fmu')

ts = 0.0 
te = 86400.
options = model.simulate_options()
idf_steps_per_hour = 6
dt = 3600./idf_steps_per_hour
ncp = (te - ts)/dt
options['ncp'] = int(ncp)

# simulation setup
model.setup_experiment(start_time=ts, stop_time=te)
model.initialize()

# initialize output dic with empty list
res = collections.defaultdict(list)

# 
t = ts
while t < te:
    # cost of comfort

    # proceed forward
    model.set('csp', 24.)
    model.set('hsp', 18.)
    model.do_step(t, dt, new_step=True)
    res['zone_temp'].append(model.get('zone_temp'))
    res['csp'].append(model.get('csp'))
    res['hsp'].append(model.get('hsp'))

    t = t + dt

Reading input and weather file for preprocessor program.
The IDF version of the input file ///tmp/JModelica.org/jm_tmp448rnaet//resources//model.idf starts with 22
Successfully finish reading weather file.
This is the Begin Month: 1
Time (0) set is smaller than minimun allowed (1 day). Day will be set to 1.
This is the Day of the Begin Month: 1
This is the End Month: 1
This is the Day of the End Month: 1
This is the New Day of Week: SUNDAY
Running EPMacro...
ExpandObjects Started.
 Begin reading Energy+.idd file.
 Done reading Energy+.idd file.
ExpandObjects Finished. Time:     0.028
EnergyPlus Starting
EnergyPlus, Version 22.2.0-c249759bad, YMD=2023.10.23 21:00
Initializing Response Factors
Calculating CTFs for "EXTERIOR WALL"
Calculating CTFs for "INTERIORFURNISHINGS"
Calculating CTFs for "EXTERIOR FLOOR"
Calculating CTFs for "INTERIOR FLOOR"
Calculating CTFs for "INTERIOR CEILING"
Calculating CTFs for "EXTERIOR ROOF"
Calculating CTFs for "EXTERIOR DOOR"
Calculating CTFs for "GABLE_E

In [5]:
res

defaultdict(list,
            {'zone_temp': [array([21.14984818]),
              array([20.71796796]),
              array([19.97144365]),
              array([19.56200272]),
              array([19.343653]),
              array([19.26049777]),
              array([19.24993391]),
              array([19.16684595]),
              array([19.07324721]),
              array([18.98917567]),
              array([18.91568455]),
              array([18.84903673]),
              array([18.77729454]),
              array([18.69711288]),
              array([18.61113739]),
              array([18.52331267]),
              array([18.43631213]),
              array([18.35131328]),
              array([18.27252495]),
              array([18.20210043]),
              array([18.13924877]),
              array([18.08203973]),
              array([18.02893718]),
              array([17.97931213]),
              array([17.93564371]),
              array([17.99844556]),
              array([17.98744259]),